# Generated by Django 3.1.3 on 2020-11-23 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_validation', 'In Validation'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='in_validation', max_length=255)),
                ('percentage', models.PositiveSmallIntegerField(choices=[(10, '10%'), (15, '15%'), (20, '20%')], default=10, help_text='percentage applied to get cashback')),
                ('cashback', models.DecimalField(decimal_places=2, default=0, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
    ]
